imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    csrf_protection: ~
    default_locale:  "en"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: ~ # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    http_method_override: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%kernel.root_dir%/../var/data/database.sqlite"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

lexik_jwt_authentication:
    private_key_path:   '%kernel.root_dir%/../var/jwt/private.pem'
    public_key_path:    '%kernel.root_dir%/../var/jwt/public.pem'
    pass_phrase:        foobar
